version: "3"
services:
  node-app:
    ports:
      - "3000:3000"
    environment:
      - "PORT=3000"
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypass
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: